library(tidyverse)
library(vegan) # Package for multivariate analyses of ecological data

setwd("/home/james/Documents/R/Multivariate_course")

#Note on variance explained
# Variance explained by ordination axes.
# In general, vegan does not directly give any statistics on the “variance explained” by ordination axes
# or by the constrained axes. This is a design decision: I think this information is normally useless and
# often misleading. In community ordination, the goal typically is not to explain the variance, but to find
# the “gradients” or main trends in the data. The “total variation” often is meaningless, and all proportions
# of meaningless values also are meaningless. Often a better solution explains a smaller part of “total variation”.
# For instance, in unstandardized principal components analysis most of the variance is generated by a small 
# number of most abundant species, and they are easy to “explain” because data really are not very multivariate.
# If you standardize your data, all species are equally important. The first axes explains much less of the
# “total variation”, but now they explain all species equally, and results typically are much more useful for 
# the whole community. Correspondence analysis uses another measure of variation (which is not variance), and 
# again it typically explains a “smaller proportion” than principal components but with a better result. 
# Detrended correspondence analysis and nonmetric multidimensional scaling even do not try to “explain” 
# the variation, but use other criteria. All methods are incommensurable, and it is impossible to compare methods
# using “explanation of variation”.
# 
# If you still want to get “explanation of variation” (or a deranged editor requests that from you),
# it is possible to get this information for some methods:
#   
# Eigenvector methods: Functions rda, cca and capscale give the variation of conditional (partialled),
# constrained (canonical) and residual components, but you must calculate the proportions by hand. 
# Function eigenvals extracts the eigenvalues, and summary(eigenvals(ord)) reports the proportions explained
# in the result object ord. Function RsquareAdj gives the R-squared and adjusted R-squared (if available) for
# constrained components. Function goodness gives the same statistics for individual species or sites (species
# are unavailable with capscale). In addition, there is a special function varpart for unbiased partitioning of
# variance between up to four separate components in redundancy analysis.
# Detrended correspondence analysis (function decorana). The total amount of variation is undefined in detrended
# correspondence analysis, and therefore proportions from total are unknown and undefined. DCA is not a method for
# decomposition of variation, and therefore these proportions would not make sense either.
# Nonmetric multidimensional scaling. NMDS is a method for nonlinear mapping, and the concept of of variation
# explained does not make sense. However, 1 - stress^2 transforms nonlinear stress into quantity analogous to
# squared correlation coefficient. Function stressplot displays the nonlinear fit and gives this statistic.



##### Read data ###########################

data("dune")
data("dune.env")

#Management factor is character but we need it to be numeric for some analyses. Convert to "dummy" variables...
#note! if you are converting a factor that is numbers already you need as.numeric(as.character(x))
dummy_management <- as.data.frame(model.matrix( ~ Management - 1, data=dune.env ))
dune.env <- dune.env %>% select(A1, Moisture, Manure, Use) %>% cbind(.,dummy_management)
dune.env$Moisture <- as.numeric(as.character(dune.env$Moisture))
dune.env$Manure <- as.numeric(as.character(dune.env$Manure))
dune.env$Use <- as.numeric(dune.env$Use)

# Read dune species dataset
dune_ulf <- read.table("Data/Data_for_R/dune.txt", sep=";",header=T,row.names=1)

# Read environmental  dataset
env_ulf<-read.table("Data/Data_for_R/env.txt", sep="\t",header=T,row.names=1)
#env$Management <- as.factor(env$Management) #convert to factor
#Management factor is character but we need it to be numeric for analyses. Convert to "dummy" variables...
#note! if you are converting a factor that is numbers already you need as.numeric(as.character(x))
#management <- env$Management #keep the character data in case we need it later
#env$Management <- as.numeric(env$Management)

#data import from zelazny
# Species and environmental data
# dune2.spe <- read.delim ('https://raw.githubusercontent.com/zdealveindy/anadat-r/master/data/dune2.spe.txt', row.names = 1)
# dune2.env <- read.delim ('https://raw.githubusercontent.com/zdealveindy/anadat-r/master/data/dune2.env.txt', row.names = 1)

# Species attributes
# dune2.traits <- read.delim ('https://raw.githubusercontent.com/zdealveindy/anadat-r/master/data/dune2.traits.txt', row.names = 1)
# dune2.ell <- read.delim ('https://raw.githubusercontent.com/zdealveindy/anadat-r/master/data/dune2.ell.txt', row.names = 1)



###########################################

#Question 2: Do a PCA on the environmental data related to the Dune meadow dataset

env.pca <- rda(dune.env, scale = TRUE)
plot(env.pca)
biplot(env.pca)
env.pca
summary(env.pca)
summary(eigenvals(env.pca))

#Question 3: Try a CA on the environmental data

#unconstrained ordination on environmental data (CA)
env.ca <- cca(dune.env) #yes, the function is called cca instead of ca
plot(env.ca)
env.ca
summary(eigenvals(env.ca)) #proportion variance explained

#Question 4: Do a CA-ordination on the Dune Meadow species dataset
#unconstrained ordination on species (CA)
dune.ca <- cca(dune)
plot(dune.ca)
dune.ca
summary(eigenvals(dune.ca))

#Question 5: Repeat exercise 4, but with DCA ordination instead. Look at the eigenvalues,
#the length of gradient, the total variation and the ordination diagram. 

dune.dca <- decorana(dune)
dune.dca
plot(dune.dca)
#Detrended correspondence analysis (function decorana). The total amount of variation
#is undefined in detrended correspondence analysis, and therefore proportions from total
#are unknown and undefined. DCA is not a method for decomposition of variation, and therefore
#these proportions would not make sense either.
